site_name: Biofilter 3.0 Documentation

nav:
  - Home: index.md
  - Biofilter: Biofilter.md
  - Loki: Loki.md

theme:
  name: "material"

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          show_submodules: true
          allow_inspection: true
          show_inheritance_diagram: true
          show_source: false