site_name: Ritchie Lab Documentation

nav:
  - Home: index.md
  - LOKI:
    - Installation: LOKI/Installation.md
    - Overview: LOKI/BriefOverview.md
    - Data Schema: LOKI/DataSchema.md
    - Knowledge Sources: LOKI/KnowledgeSources.md
  - Biofilter: 
    - Installation: Biofilter/Installation.md
    - Configuration: Biofilter/Configuration.md
    - Input File Format: Biofilter/InputFileFormats.md
    - Output File Format: Biofilter/OutputFileFormats.md
    - Command Arguments: Biofilter/BiofilterArguments.md
    - Appendix: Biofilter/Appendix.md
  - Tutorials:
    - Filtering: Tutorials/FilteringExamples.md
    - Annotation: Tutorials/AnnotationExamples.md
    - Modeling: Tutorials/ModelingExamples.md
    - Combination: Tutorials/FilteringFollowedByAnnotationExamples.md
    - PARIS: Tutorials/PARIS.md
    - Simulated Examples: Tutorials/SimulatedDataExamples.md
  - For Developers: 
      - Biofilter Dev: ForDevelopers/Biofilter_docstring.md
      - LOKI Dev: ForDevelopers/Loki_docstring.md
      - Code and References: ForDevelopers/CodeAndReferences.md
      - Deprecated Versions: ForDevelopers/DeprecatedVersions.md

theme:
  name: readthedocs
extra_css: 
  - style.css

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          allow_inspection: true
          show_inheritance_diagram: true
          show_source: false
