site_name: Ritchie Lab Documentation

nav:
  - Home: index.md
  - Biofilter: 
    - Installation: Biofilter/Installation.md
    - Development: 
      - Biofilter: Biofilter/Development/Biofilter_docsring.md
      - LOKI: Biofilter/Development/Loki_docsring.md

theme:
  name: "material"

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          allow_inspection: true
          show_inheritance_diagram: true
          show_source: false
