[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Biofilter"
authors = [{name = "Li", email = "xueqiong.li@pennmedicine.upenn.edu"}]
dynamic = ["version", "description"]